### PR TITLE
OPA-80: Develop custom eslint rule to check named constructors

### PR DESCRIPTION
**Pull request by Grygir**

### CODE REVIEW

**Comment by sergeyz** [comment]
Please move this package into monorepo and configure split

**Comment by Grygir** [comment]
@sergeyz, will do it separately late

**Comment by sergeyz** [comment]
@Grygir  You'll have a lot of issues with non-empty repository later, same time including this to monorepo will simplify lib testing a lot

**Comment by mbessolov** [comment]
@sergeyz we can always wipe out this repository and start from scratch.

**Pull request merged**
